version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: newsphp-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: newsphp-nginx
    restart: always
    ports:
      - "8000:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: newphp-db
    image: mysql:8.0
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./storage/mysql:/var/lib/mysql
    user: "1000:50"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"